[project]
name = "classification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "numpy",
    "pandas",
    "tensorflow",
]

[tool.uv]
dev-dependencies = []
